name: Change Version

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  update_version:
    runs-on: ubuntu-latest
    outputs:
      CHANGE_VERSION_TYPE: ${{steps.version_change.outputs.change_version_type}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install jp -y

      - name: Determine version Change
        id: version_change
        run: |
          PR_TITLE=$(jq -r ".pull_request.title" "$GITHUB_EVENT_PATH")

          if [[ $PR_TITLE == "feat:"* ]]; then            
            CHANGE_VERSION_TYPE=minor
          elif [[ $PR_TITLE == "fix:"* ]]; then
            CHANGE_VERSION_TYPE=patch            
          else
            CHANGE_VERSION_TYPE=undefined            
          fi

          echo $CHANGE_VERSION_TYPE >> "$GITHUB_OUTPUT"
          echo "Change version type: $CHANGE_VERSION_TYPE"

      - name: Update version.json
        env:
          CHANGE_VERSION_TYPE: ${{steps.version_change.outputs.change_version_type}}
        run: |
          CURRENT_VERSION=$(jq -r ".version" version.json)
          MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
          MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
          PATCH=$(echo $CURRENT_VERSION | cut -d. -f3)
          if [[ $CHANGE_VERSION_TYPE == "minor" ]]; then
            NEW_VERSION="$MAJOR.$((MINOR + 1)).0"
          elif [[ $CHANGE_VERSION_TYPE == "patch" ]]; then
            NEW_VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
          fi
          echo "update type: $CHANGE_VERSION_TYPE - change version from $CURRENT_VERSION to $NEW_VERSION"
          jq --arg new_version "$NEW_VERSION" '.version = $new_version' version.json > version.tmp && mv version.tmp version.json
