name: Change Version

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  update_version:
    runs-on: ubuntu-latest
    outputs:
      CHANGE_VERSION_TYPE: ${{steps.version_change.outputs.change_version_type}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install jp -y

      - name: Determine version Change
        id: version_change
        run: |
          PR_TITLE=$(jq -r ".pull_request.title" "$GITHUB_EVENT_PATH")
          if [[ $PR_TITLE == "feat:"* ]]; then
            echo "change_version_type=minor" >> "$GITHUB_OUTPUT"
          elif [[ $PR_TITLE == "fix:"* ]]; then
            echo "change_version_type=patch" >> "$GITHUB_OUTPUT"
          else
            echo "change_version_type=undefined" >> "$GITHUB_OUTPUT"
          fi

      - name: Update version.json
        env:
          CHANGE_VERSION_TYPE: ${{steps.version_change.outputs.change_version_type}}
        run: |
          CURRENT_VERSION=$(jq -r ".version" version.json)
          MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
          MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
          PATCH=$(echo $CURRENT_VERSION | cut -d. -f3)
          if [[ $CHANGE_VERSION_TYPE == "minor" ]]; then
            NEW_VERSION="$MAJOR.$((MINOR + 1)).0"
          elif [[ $CHANGE_VERSION_TYPE == "patch" ]]; then
            NEW_VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
          fi
          echo "update type: $CHANGE_VERSION_TYPE - current version: $CURRENT_VERSION - new version: $NEW_VERSION"
