name: Change Version

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  update_version:
    runs-on: ubuntu-latest
    outputs:
      CHANGE_VERSION_TYPE: ${{steps.version_change.outputs.change_version_type}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install jp -y

      - name: Determine version Change
        id: version_change
        run: |
          PR_TITLE=$(jq -r ".pull_request.title" "$GITHUB_EVENT_PATH")

          if [[ $PR_TITLE == "feat:"* ]]; then            
            CHANGE_VERSION_TYPE=minor
          elif [[ $PR_TITLE == "fix:"* ]]; then
            CHANGE_VERSION_TYPE=patch            
          else
            CHANGE_VERSION_TYPE=undefined            
          fi

          echo "change_version_type=$CHANGE_VERSION_TYPE" >> "$GITHUB_OUTPUT"
          echo "Change version type: $CHANGE_VERSION_TYPE"

      - name: Update version.json
        env:
          CHANGE_VERSION_TYPE: ${{steps.version_change.outputs.change_version_type}}
          CURRENT_BRANCH: ${{github.event.pull_request.head.ref}}
        run: |
          CURRENT_VERSION=$(jq -r ".version" version.json)
          MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
          MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
          PATCH=$(echo $CURRENT_VERSION | cut -d. -f3)
          if [[ $CHANGE_VERSION_TYPE == "minor" ]]; then
            NEW_VERSION="$MAJOR.$((MINOR + 1)).0"
          elif [[ $CHANGE_VERSION_TYPE == "patch" ]]; then
            NEW_VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
          fi
          echo "update type: $CHANGE_VERSION_TYPE - change version from $CURRENT_VERSION to $NEW_VERSION"
          jq --arg new_version "$NEW_VERSION" '.version = $new_version' version.json > version.tmp && mv version.tmp version.json
          git config --global user.email "auto.version.actions@noreply.github.com"
          git config --global user.name "Auto-update version actions"
          git add version.json
          git commit -m "chore: update version.json with $NEW_VERSION $CHANGE_VERSION_TYPE version"
          git status
