name: Change Version

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  update_version:
    runs-on: ubuntu-latest
    outputs:
      CHANGE_VERSION_TYPE: ${{steps.version_change.outputs.change_version_type}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install jp -y

      - name: Determine version Change
        id: version_change
        run: |
          PR_TITLE=$(jp -r ".pull_request.title" "$GITHUB_EVENT_PATH")
          if [[ $PR_TITLE == "feat:"* ]]; then
            echo "change_version_type=minor" >> "$GITHUB_OUTPUT"
          elif [[ $PR_TITLE == "fix:"* ]]; then
            echo "change_version_type=patch" >> "$GITHUB_OUTPUT"
          else
            echo "change_version_type=undefined" >> "$GITHUB_OUTPUT"
          fi

      - name: Update version.json
        env:
          CHANGE_VERSION_TYPE: ${{steps.version_change.outputs.change_version_type}}
        run: |
          echo "update type: $CHANGE_VERSION_TYPE"
